AWSTemplateFormatVersion: "2010-09-09"
Description: A sample creation of VPC template
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties: 
       ImageId: ami-06aa3f7caf3a30282
       InstanceType: t2.micro

     